# Generated by Django 5.0.7 on 2024-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('parking_address', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('selected_option', models.CharField(max_length=50)),
                ('moto_option', models.CharField(blank=True, max_length=50)),
                ('annulation', models.BooleanField()),
                ('purchase_date', models.DateField()),
                ('project_purchase', models.BooleanField()),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('first_registration_date', models.DateField()),
                ('acquisition_date', models.DateField()),
                ('permis_a1', models.DateField(blank=True, null=True)),
                ('permis_a2', models.DateField(blank=True, null=True)),
                ('permis_a', models.DateField(blank=True, null=True)),
                ('permis_b', models.DateField(blank=True, null=True)),
                ('annulation_a1', models.BooleanField()),
                ('annulation_a2', models.BooleanField()),
                ('annulation_a', models.BooleanField()),
                ('annulation_b', models.BooleanField()),
                ('additional_info', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
