# Generated by Django 5.0.7 on 2024-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
